### login
POST https://jwt-auth-eight-neon.vercel.app/login
Content-Type: application/json

{
  "email": "111202315326@mhs.dinus.ac.id",
  "password": "123456"
}

### logout
POST https://jwt-auth-eight-neon.vercel.app/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzNywibmFtZSI6IkFCSElSQU1BIiwiZW1haWwiOiIxMTEyMDIzMTUzNTNAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgwOTg3NjI5LCJleHAiOjE3ODEwNzQwMjl9.IRkneJVGrwafZMORf77QOgU4IZ6zxiD1DuhTDFQkkNU