### get goals
GET https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzNywibmFtZSI6IkFCSElSQU1BIiwiZW1haWwiOiIxMTEyMDIzMTUzNTNAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgwOTg3NjI5LCJleHAiOjE3ODEwNzQwMjl9.IRkneJVGrwafZMORf77QOgU4IZ6zxiD1DuhTDFQkkNU

### post goals
POST https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzNywibmFtZSI6IkFCSElSQU1BIiwiZW1haWwiOiIxMTEyMDIzMTUzNTNAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgwOTg3NjI5LCJleHAiOjE3ODEwNzQwMjl9.IRkneJVGrwafZMORf77QOgU4IZ6zxiD1DuhTDFQkkNU
Content-Type: application/json

{
  "target_amount": 5000,
  "present_amount": 2100
}